package com.example.rooster.data.model

enum class DisputeType { ORDER_ISSUE, PRODUCT_DAMAGED, PAYMENT_PROBLEM, OTHER }

enum class DisputeStatus { PENDING, REVIEWED, RESOLVED }

data class DisputeRecord(
    val id: String = "", // generated by backend
    val userId: String,
    val type: DisputeType,
    val message: String,
    val mediaUrls: List<String> = emptyList(),
    val relatedOrderId: String? = null,
    val productId: String? = null,
    val status: DisputeStatus = DisputeStatus.PENDING,
    val createdAt: Long = System.currentTimeMillis(),
)
