package com.example.rooster.feature.community.domain.model

import kotlinx.serialization.Serializable

@Serializable // If it needs to be serialized for other purposes, though RTDB uses Map/primitive
data class ChatMessage(
    val messageId: String = "", // Can be auto-generated by RTDB push()
    val chatRoomId: String = "", // Identifies the conversation
    val senderId: String = "",
    val senderDisplayName: String = "", // Denormalized for display
    val senderProfilePictureUrl: String? = null, // Denormalized
    val text: String? = null,
    val imageUrl: String? = null, // For image messages
    val timestamp: Long = System.currentTimeMillis(),
    val isRead: Boolean = false
    // val messageType: String = "TEXT" // e.g. TEXT, IMAGE, etc.
)
