name: CI - Android Unit Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build and run unit tests
        run: ./gradlew test
      - name: Generate JaCoCo coverage report
        run: ./gradlew jacocoTestReport
      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: app/build/jacocoHtml
