name: Full CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: chmod +x ./gradlew
      - run: ./gradlew test
      - run: ./gradlew jacocoTestReport
      - uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: app/build/jacocoHtml

  build-test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test

  build-test-cloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloud
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      # Add cloud function tests here if available

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew lint

  # Add deployment jobs as needed (e.g., Docker, Firebase, Parse, etc.)
