name: Security Audit

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  audit-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - name: Run npm audit
        run: npm audit --audit-level=moderate || true
      - name: Run ESLint
        run: npx eslint . || true

  audit-cloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloud
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - name: Run npm audit
        run: npm audit --audit-level=moderate || true
      - name: Run ESLint
        run: npx eslint . || true

  audit-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run dependency check (OWASP)
        run: |
          curl -LJO https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check-8.4.0-release.zip -d dependency-check
          ./dependency-check/bin/dependency-check.sh --project "Rooster Android" --scan app/ --format HTML --out dependency-check-report
        continue-on-error: true
      - name: Upload dependency check report
        uses: actions/upload-artifact@v3
        with:
          name: android-dependency-check
          path: dependency-check-report
